// Do not edit. This file is machine generated by the Resource DLL Wizard.

library richedit;

{ITE} {LCID:00000409:00000409} {}
{ITE} {DFMFileType} {reabout.dfm}
{ITE} {DFMFileType} {remain.dfm}
{ITE} {RCFileType} {richedit_DRC.rc}

{$R 'reabout.dfm' AboutBox:TForm}
{$R 'remain.dfm' MainForm:TForm}
{$R 'richedit_DRC.res' 'richedit_DRC.rc'}

{$E ENU}

begin
end.